config/routes.rb
Rails.application.routes.draw do
  resource :profile, except: [:destroy]
  root 'orders#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    resources :plates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  board      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Order < ApplicationRecord
  has_and_belongs_to_many :plates
  belongs_to :user
  # validaciones
  validates :board, presence: true

  def profile
    user.profile
  end

  def user_name
    profile.name
  end
end

app/models/plate.rb
# == Schema Information
#
# Table name: plates
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  price       :decimal(10, 2)
#  available   :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Plate < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  name       :string
#  last_name  :string
#  rol        :string
#  salary     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :signed_in_no_profile
  def signed_in_no_profile
    if signed_in? && current_user.profile.nil?
      redirect_to new_profile_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
      #redirect_to order_path(@order.id)
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render :edit
    end
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:board, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  skip_before_action :signed_in_no_profile, only: [:new, :create]

  def show
    @profile = current_user.profile
  end

  def edit
    @profile  = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to :orders
    else
      render :new
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:name, :last_name, :rol, :salary).merge(user: current_user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yummi</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Google fonts -->
  <link href='https://fonts.googleapis.com/css?family=Caveat Brush' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Graduate' rel='stylesheet'>
</head>

<body class="<%=user_signed_in? ? "white-body" : "purple-body" %>">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
          <div class="logo-con-txt flex">
            <p class="logo-txt">Yummii</p>
          </div>
        </div>
        <div class="col-xs-4">
          <ul class="nav navbar-nav navbar-right flex-row">
            <% if user_signed_in? %>
            <li><%= link_to current_user.email, profile_path%><i class="fas fa-caret-square-down"></i></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
            <li><%= link_to('Sign up', new_user_registration_path) %></li>
            <li>
              <%= link_to('Login', new_user_session_path) %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xs-8 justify-content-center flex">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/orders/_form.html.erb
    <div class="col-xs-12 flex-column">
  <div class="panel panel-default devise-bs">
    <div class="panel-body">
      <%= form_for(@order) do |f| %>

        <% if @order.errors.any? %>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
              <li> <%= msg.to_s %> </li>
            <% end%>
          </ul>
        <% end %>
        <div class="form-group">
          <%= f.label :board %>
          <%= f.text_field :board, class:"field-input"%>
        </div>
        <div class="form-group">
          <%= f.label :user_id %>
          <%= collection_select(:order, :user_id, Profile.all, :id, :name, prompt: true) %>
        <div>
        <div class="col-12 cont_order_btn-f flex">
          <%= f.submit class: 'btn btn-yummi' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/orders/edit.html.erb
<div class="col-xs-6">
  <h1 class="txt-undeline">Edit order</h1>
  <%= render 'form' %>
</div>

app/views/orders/index.html.erb
<div class="col-xs-12">
  <h2 class="txt-undeline">Orders</h2>
  <hr>

  <!-- <%= link_to 'Nuevo', new_order_path if user_signed_in? %> -->
  <div class="cont-create-btn"><%= button_to "create new order", new_order_path, :method => "get", class: 'btn btn-yummi-outline' %>  </div>

  <!-- <%=  @orders.inspect  %></p> -->
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>Employee</th>
        <th>Table</th>
        <th>Order detail</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.profile.name.to_s + " " +order.profile.last_name.to_s %></td>
        <td><%= order.board %></td>
        <td>
          <%= link_to order_path(order) do %>
              <i class="fas fa-eye icon-crud"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_order_path(order) do %>
              <i class="fas fa-edit icon-crud"></i>
          <% end %>
        </td>
        <td><%= link_to "X", order_path(order), method: :delete,  data: {confirm: '¿Are you sure?'}, class: 'red-icon' %></td>
      </tr>
    </tbody>
    <%end%>
  </table>

</div>

app/views/orders/new.html.erb
<div class="col-xs-6">
  <h1>Take order</h1>
  <%= render 'form'%>
</div>

app/views/orders/show.html.erb
<!-- <div class="container-fluid">
  <div class="row">
    <div class="hipster-box justify-content-center"><p class="">Order</p></div>
  </div> -->
    <!-- <%= @order.inspect %> -->
  <div class="row justify-content-center">
    <div class="card">
      <!-- <img class="card-img-top" src="people.png" alt="Card image cap"> -->
      <%= image_tag("food.jpeg", :alt => "waiter")%>
      <div class="card-body">

        <div class="col-12 flex-end">
          <p class="title-purple">
            Edit
            <%= link_to edit_order_path(@order) do %>
            <i class="fas fa-edit icon-crud"></i>
            <% end %>
          </p>
        </div>


        <h5 class="card-title"><p class="title-purple"> Order: </p> <%= @order.id %></h5>
        <p class="card-text"><p class="title-purple"> Waiter: </p> <%= @order.profile.name.to_s + " " +@order.profile.last_name.to_s %></p>
        <p class="card-text"><p class="title-purple"> Order at: </p>Order at: <%= @order.created_at %> </p>
        <p class="card-text"><p class="title-purple"> Updated at:  </p> <%= @order.updated_at %> </p>
      </div>
      <div class="col-12 cont-btn-yummi">
        <%= button_to "Back to orders", orders_path, :method => "get", class: 'btn btn-yummi' %>
       </div>
    </div>


  </div>


</div>

app/views/profiles/_form.html.erb
<div class="col-xs-12 flex-column">
  <div class="panel panel-default devise-bs">
    <div class="panel-body">
      <%= form_for(@profile, url: profile_path(@profile)  ) do |f| %>

        <% if @profile.errors.any? %>
          <ul>
          <% @profile.errors.full_messages.each do |msg| %>
            <li><%= msg.to_s %> </li>
          <% end %>
          </ul>
        <% end %>
        <div class="form-group">
          <p><%= f.label :name %></p>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <p style="display:block"><%= f.label :last_name %></p>
          <%= f.text_field :last_name %>
        </div>
        <div class="form-group">
          <p style="display:block"><%= f.label :rol %></p>
          <%= f.text_field :rol %><br>
        </div>

        <div class="form-group">
          <p style="display:block"><%= f.label :salary %></p>
          <%= f.number_field :salary %>
        </div>
        <div class="col-12 flex">
          <%= f.submit class: 'btn btn-yummi' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="col-xs-6">
  <h1>Edit</h1>
  <%= render "form" %>
  <div class="cont-back-form">
      <%= button_to "Back to orders", orders_path, :method => "get", class: 'btn btn-yummi-outline' %>
  </div>

</div>

app/views/profiles/new.html.erb
<div class="col-xs-6">
  <h2 class="txt-undeline">New Employee</h2>
  <% if @profile %>
      <p class="greet">Hi,before we start we need this information ;)</p>
  <% end%>
  <%= render 'form' %>
</div>

app/views/profiles/show.html.erb
<div class="row justify-content-center flex-column">
  <h2 class="txt-undeline">Show Profile</h2>
  <% if @profile %>
    <div class="card">
        <%= image_tag("waiter.jpg", :alt => "waiter" , class: "card-img-top img-card") %>
        <div class="card-body">
          <div class="col-12 flex-end">
            <p class="title-purple">
              Edit
              <%= link_to edit_profile_path(@profile) do %>
              <i class="fas fa-edit icon-crud"></i>
              <% end %>
            </p>
          </div>

          <h5 class="card-title"><p class="title-purple"> Profile: </p> <%= @profile.id %></h5>
          <p class="card-text"><p class="title-purple"> Name: </p> <%= @profile.name.to_s + " " +@profile.last_name.to_s %></p>
          <p class="card-text"><p class="title-purple"> Email: </p> <%= @profile.user.email %></p>
          <p class="card-text"><p class="title-purple"> Job: </p> <%= @profile.rol %> </p>
          <p class="card-text"><p class="title-purple"> Salary:  </p> <%= @profile.salary %> </p>
          <p class="card-text"><p class="title-purple"> job start date:  </p> <%= @profile.created_at %> </p>

        </div>
    </div>
    <div class="col-12 cont-btn-yummi" style="margin-top:20px">
      <%= button_to "Back to orders", orders_path, :method => "get", class: 'btn btn-yummi' %>
     </div>
    <!-- <%= link_to "Editar", edit_profile_path(@profile)  %> -->
  <%else %>
    <%= link_to "Crear", new_profile_path %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>